### ISSUE TITLE
使用!plugin <储存库地址>    从Git储存库安装插件的指令安装该插件会报错？

### ISSUE THREAD

**Issue by flysmart** [chordfish-k/QChartGPT_Emoticon_Plugin#1]
这个插件是不是暂时还不能用？

**Comment by RockChinQ** [comment]
报了啥错，贴一下

**Comment by flysmart** [comment]
![4N$INJ~3(0M(~YA1FB4 TJC](https://user-images.githubusercontent.com/66983043/227108491-71697b5c-9c74-4a6d-afee-3cd18e200b02.png)

**Comment by flysmart** [comment]
我把import 语句emotin.config 改成QChartGPT_Emoticon_Plugin.config就可以了 打扰了

**Comment by chordfish-k** [comment]
使用该指令默认以仓库名作为文件夹名
从而导致config包名路径与文件夹名不一致
现已修复
